/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * NVDA Alerts API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type AlertDirection =
  (typeof AlertDirection)[keyof typeof AlertDirection];

export const AlertDirection = {
  above: "above",
  below: "below",
} as const;

export interface Alert {
  id: number;
  targetPrice: number;
  direction: AlertDirection;
  /** @nullable */
  note?: string | null;
  isActive: boolean;
  isTriggered: boolean;
  /** @nullable */
  triggeredAt?: string | null;
  /** @nullable */
  triggeredPrice?: number | null;
  createdAt: string;
  updatedAt?: string;
}

export type AlertInputDirection =
  (typeof AlertInputDirection)[keyof typeof AlertInputDirection];

export const AlertInputDirection = {
  above: "above",
  below: "below",
} as const;

export interface AlertInput {
  /** @minimum 0.01 */
  targetPrice: number;
  direction: AlertInputDirection;
  note?: string;
}

export type AlertUpdateDirection =
  (typeof AlertUpdateDirection)[keyof typeof AlertUpdateDirection];

export const AlertUpdateDirection = {
  above: "above",
  below: "below",
} as const;

export interface AlertUpdate {
  /** @minimum 0.01 */
  targetPrice?: number;
  direction?: AlertUpdateDirection;
  note?: string;
  isActive?: boolean;
}

export interface AlertsSummary {
  total: number;
  active: number;
  triggered: number;
  inactive: number;
  /** @nullable */
  currentPrice: number | null;
  /** @nullable */
  nearestAlertPrice?: number | null;
  /** @nullable */
  nearestAlertDirection?: string | null;
}

export interface StockQuote {
  ticker: string;
  price: number;
  /** @nullable */
  change?: number | null;
  /** @nullable */
  changePercent?: number | null;
  /** @nullable */
  high?: number | null;
  /** @nullable */
  low?: number | null;
  /** @nullable */
  open?: number | null;
  /** @nullable */
  previousClose?: number | null;
  /** @nullable */
  volume?: number | null;
  /** @nullable */
  marketCap?: number | null;
  updatedAt: string;
}

export interface PricePoint {
  date: string;
  price: number;
  /** @nullable */
  open?: number | null;
  /** @nullable */
  high?: number | null;
  /** @nullable */
  low?: number | null;
  /** @nullable */
  volume?: number | null;
}

export interface OverallStats {
  total: number;
  wins: number;
  losses: number;
  expired: number;
  winRate: number;
  avgContractPnl: number;
}

export interface TickerStats {
  ticker: string;
  total: number;
  wins: number;
  losses: number;
  expired: number;
  winRate: number;
}

export type TradeRecordSignal =
  (typeof TradeRecordSignal)[keyof typeof TradeRecordSignal];

export const TradeRecordSignal = {
  CALL: "CALL",
  PUT: "PUT",
} as const;

export type TradeRecordCloseReason =
  (typeof TradeRecordCloseReason)[keyof typeof TradeRecordCloseReason];

export const TradeRecordCloseReason = {
  tp1: "tp1",
  tp2: "tp2",
  tp3: "tp3",
  stop: "stop",
  expired: "expired",
} as const;

export interface TradeRecord {
  id: number;
  ticker: string;
  signal: TradeRecordSignal;
  confidence: number;
  closeReason: TradeRecordCloseReason;
  pnlPct: number;
  contractEntry: number;
  contractHigh: number;
  closedAt: string;
}

export interface TradingStats {
  overall: OverallStats;
  byTicker: TickerStats[];
  recent: TradeRecord[];
}

export type ListAlertsParams = {
  status?: ListAlertsStatus;
};

export type ListAlertsStatus =
  (typeof ListAlertsStatus)[keyof typeof ListAlertsStatus];

export const ListAlertsStatus = {
  active: "active",
  inactive: "inactive",
  triggered: "triggered",
  all: "all",
} as const;
